# The image will be at ghcr.io/yourusername/name
name: cerulean

# The native container image to build on top of
# images. 
# Warning: Non-uBlue images might function unexpectly
base-container: ghcr.io/ublue-os/kinoite-main

# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this). 
fedora-version: 38

# This description will be visible in the container metadata
description: An opinionated Fedora Kinoite spin using uBlue-os tooling. 

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - python3-pip # needed for yafti (the first boot installer)
  # ClamAV and associated packages
  - clamav-freshclam
  - clamd
  - clamtk
  # Fcitx input
  - fcitx5-chinese-addons
  - fcitx5-configtool
  - fcitx5-gtk
  - fcitx5-qt
  - fcitx5-table-extra
  - fcitx5-table-other
  # Multimedia codecs, etc.
  - gstreamer1-plugin-openh264
  - mozilla-openh264
  - openh264
  # Network
  - plasma-nm-fortisslvpn
  - syncthing
  # Office programs
  - libreoffice
  - libreoffice-kf5
  - cups-pdf
  - gimagereader-qt
  - hunspell-fr
  - skanpage
  - tesseract-langpack-chi_sim
  - tesseract-langpack-chi_tra
  - tesseract-langpack-fra
  # System management
  - igt-gpu-tools
  - kcron
  - lm_sensors
  - neofetch
  - seahorse
  # Virtualisation (from dnf groupinfo virtualization)
  - guestfs-tools
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - libvirt-daemon-system
  - python3-libguestfs
  - qemu-kvm
  - virt-install
  - virt-manager
  - virt-top
  - virt-viewer
  # Misc
  - mono-core
  - squashfs-tools

# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - ca.hamaluik.Timecop
  - ch.theologeek.Manuskript
  - com.authy.Authy
  - com.borgbase.Vorta
  - com.discordapp.Discord
  - com.github.PintaProject.Pinta
  - com.github.zocker_160.SyncThingy
  - com.moonlight_stream.Moonlight
  - com.parsecgaming.parsec
  - com.skype.Client
  - com.valvesoftware.Steam
  - com.wire.WireDesktop
  - in.srev.guiscrcpy
  - io.crow_translate.CrowTranslate
  - io.github.dosbox-staging
  - io.github.giantpinkrobots.bootqt
  - io.github.jacalz.rymdport
  - org.atheme.audacious
  - org.chromium.Chromium
  - org.chromium.Chromium.Codecs
  - org.freeplane.App
  - org.keepassxc.KeePassXC
  - org.mozilla.Thunderbird
  - org.prismlauncher.PrismLauncher
  - org.signal.Signal
  - org.telegram.desktop
  - org.telegram.desktop.webview
  - org.videolan.VLC
  - org.zotero.Zotero
  - us.zoom.Zoom
